esmvc:
  scrollcache:
    local-cache-max-capacity: 30
  rest:
    primary:
      name: testRest
      nodes: 192.168.1.64:9200
      protocol: https
      search-guard-ssl:
        enable: true
        pemcertFilepath: classpath:ssl/common client.pem
        pemkeyFilepath: classpath:ssl/common client.key
        pemkeyPassword: LmqZy28M3lHBfcJuD9tL
        pemtrustedcasFilepath: classpath:ssl/root-ca.pem
        SSLHostnameVerifiers:
          - 192.168.1.64
      username: admin
      password: admin
  tcp:
    primary:
      name: testTcp
      nodes: 192.168.1.64:9300
      plugins:
        - com.floragunn.searchguard.ssl.SearchGuardSSLPlugin
      props:
        "[client.transport.sniff]": true # 是否启用sniff方案获取可用集群nodes
        "[client.transport.nodes_sampler_interval]": 60s
        "[client.transport.ignore_cluster_name]": false
        "[cluster.name]": my-application # 当集群名称不忽略时，该名称必须是存在的集群名称
        "[searchguard.ssl.transport.pemkey_filepath]": ${esmvc.rest.primary.search-guard-ssl.pemkeyFilepath} #classpath:ssl/common client.key
        "[searchguard.ssl.transport.pemcert_filepath]": ${esmvc.rest.primary.search-guard-ssl.pemcertFilepath} #classpath:ssl/common client.pem
        "[searchguard.ssl.transport.pemtrustedcas_filepath]": ${esmvc.rest.primary.search-guard-ssl.pemtrustedcasFilepath} #classpath:ssl/root-ca.pem
        "[searchguard.ssl.transport.pemkey_password]": ${esmvc.rest.primary.search-guard-ssl.pemkeyPassword} #LmqZy28M3lHBfcJuD9tL
        "[searchguard.ssl.transport.enforce_hostname_verification]": false
swagger:
  base-package: com.jn.esmvc.examples

